[package]
name = "weaver-build-util"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
cap-std = { workspace = true }
camino = { workspace = true }
time = { version = "0.3", features = ["formatting"] }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
