//! Stable reason codes for plugin refusal diagnostics.
//!
//! When a plugin cannot complete a requested operation, it returns a
//! failed response with one or more diagnostics. Each diagnostic may
//! carry a [`ReasonCode`] that callers can match programmatically
//! without parsing human-readable messages.
//!
//! Reason codes are serialized as `snake_case` strings for stability
//! across protocol versions.

use serde::{Deserialize, Serialize};

/// Stable reason code for a plugin refusal diagnostic.
///
/// Reason codes enable callers to react programmatically to specific
/// failure conditions without parsing free-text messages.
///
/// # Example
///
/// ```
/// use weaver_plugins::capability::ReasonCode;
///
/// let code = ReasonCode::SymbolNotFound;
/// assert_eq!(code.as_str(), "symbol_not_found");
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReasonCode {
    /// The symbol at the requested position could not be resolved.
    SymbolNotFound,
    /// The symbol is generated by a macro and cannot be renamed directly.
    MacroGenerated,
    /// Multiple definitions or references are ambiguous.
    AmbiguousReferences,
    /// The requested language is not supported by the plugin.
    UnsupportedLanguage,
    /// The request payload is missing required fields or has invalid values.
    IncompletePayload,
    /// The new name conflicts with an existing symbol in scope.
    NameConflict,
    /// The plugin does not support the requested operation.
    OperationNotSupported,
}

impl ReasonCode {
    /// Returns the canonical `snake_case` string for this reason code.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::SymbolNotFound => "symbol_not_found",
            Self::MacroGenerated => "macro_generated",
            Self::AmbiguousReferences => "ambiguous_references",
            Self::UnsupportedLanguage => "unsupported_language",
            Self::IncompletePayload => "incomplete_payload",
            Self::NameConflict => "name_conflict",
            Self::OperationNotSupported => "operation_not_supported",
        }
    }
}

impl std::fmt::Display for ReasonCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}
