name: Upload release artefacts
description: Upload staged artefacts to a GitHub release or validate them in dry-run mode.
inputs:
  release-tag:
    description: Git tag identifying the release to publish to.
    required: true
  bin-name:
    description: Binary name used to derive artefact names.
    required: true
  dist-dir:
    description: Directory containing staged artefacts.
    required: false
    default: dist
  dry-run:
    description: When true, only validate artefacts and print the upload plan.
    required: false
    default: "false"
outputs:
  upload-error:
    description: Whether the invocation detected an error.
    value: ${{ steps.invoke.outputs.upload-error }}
  error-message:
    description: Summary of the error when ``upload-error`` is ``true``.
    value: ${{ steps.invoke.outputs.error-message }}
runs:
  using: composite
  steps:
    - id: invoke
      name: Upload release artefacts
      shell: bash
      env:
        INPUT_RELEASE_TAG: ${{ inputs.release-tag }}
        INPUT_BIN_NAME: ${{ inputs.bin-name }}
        INPUT_DIST_DIR: ${{ inputs.dist-dir }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -uo pipefail

        dist_dir="${INPUT_DIST_DIR:-dist}"
        release_tag="${INPUT_RELEASE_TAG}"
        dry_run="${INPUT_DRY_RUN:-false}"

        if [[ ! -d "$dist_dir" ]]; then
          echo "upload-error=true" >> "$GITHUB_OUTPUT"
          echo "error-message=Distribution directory '$dist_dir' not found" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Find all artefact directories
        artefact_dirs=$(find "$dist_dir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null || true)

        if [[ -z "$artefact_dirs" ]]; then
          echo "upload-error=true" >> "$GITHUB_OUTPUT"
          echo "error-message=No artefact directories found in '$dist_dir'" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        upload_errors=()

        for dir in $artefact_dirs; do
          echo "Processing artefacts in: $dir"

          # Find all files to upload (excluding directories)
          files=$(find "$dir" -type f 2>/dev/null || true)

          for file in $files; do
            if [[ "$dry_run" == "true" ]]; then
              echo "[DRY-RUN] Would upload: $file"
            else
              echo "Uploading: $file"
              if ! gh release upload "$release_tag" "$file" --clobber 2>&1; then
                upload_errors+=("Failed to upload: $file")
              fi
            fi
          done
        done

        if [[ ${#upload_errors[@]} -gt 0 ]]; then
          echo "upload-error=true" >> "$GITHUB_OUTPUT"
          {
            echo "error-message<<EOF"
            printf '%s\n' "${upload_errors[@]}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        else
          echo "upload-error=false" >> "$GITHUB_OUTPUT"
          echo "error-message=" >> "$GITHUB_OUTPUT"
        fi
